// Generated by CoffeeScript 1.9.2
(function() {
  var Convol, Input, InputMassive, Keywords, Literals, Output, Separators, deleteConvol, doBrackets, doTranspon, doUnar, isKeyword, isLiteral, isNumber, isSeparator, lexicalAnalysis, preRes, streamWords, syntaxAnalys, value_command,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  Input = document.getElementById("input-area");

  Output = document.getElementById("output-area");

  Input.value = "";

  Output.value = "";

  InputMassive = [];

  Convol = [];

  value_command = [];

  preRes = [];

  Keywords = ["ROWVECTOR", "COLVECTOR", "MATRIX", "PRINT"];

  Separators = ["(", ",", ")", "=", "+", "-", "*", "^", "@"];

  Literals = [];


  /* */

  console.log("courseos@razumov:~> Let's test!");

  streamWords = function() {
    var i, j, k, len, num_n, ref, stage, word;
    stage = Input.value;
    num_n = -1;
    if (event.keyCode === 13) {
      for (j = 0, len = stage.length; j < len; j++) {
        word = stage[j];
        for (i = k = 0, ref = word.length; 0 <= ref ? k <= ref : k >= ref; i = 0 <= ref ? ++k : --k) {
          if (word.charAt(i) === "\n") {
            num_n++;
          }
        }
      }
      InputMassive = stage.split("\n");
      lexicalAnalysis(InputMassive, num_n);
      Convol.push([0, 0]);
      return syntaxAnalys();
    }
  };

  lexicalAnalysis = function(arr, n) {
    var i, iK, iL, iN, iS, j, preResult, ref, ref1, ref2, results, word;
    word = arr[n];
    console.log(word);
    word = word.replace(/\s+$/, "");
    preResult = "";
    results = [];
    for (i = j = 0, ref = word.length; 0 <= ref ? j <= ref : j >= ref; i = 0 <= ref ? ++j : --j) {
      if ((ref1 = word.charAt(i), indexOf.call(Separators, ref1) >= 0) || word.charAt(i) === ' ' || i === word.length) {
        iK = isKeyword(preResult, word);
        if (iK === false) {
          iL = isLiteral(preResult, word);
        }
        iN = isNumber(preResult, word);
        iS = isSeparator(word.charAt(i), word);
        if (iK === true) {
          preResult = "";
          continue;
        }
        if (iS === true) {
          preResult = "";
          continue;
        }
        if (iL === true) {
          preResult = "";
          continue;
        }
        if (iN === true) {
          preResult = "";
          continue;
        }
        if (ref2 = word.charAt(i - 1), indexOf.call(Separators, ref2) >= 0) {
          continue;
        }
        if (word.charAt(i - 1) === " ") {
          continue;
        }
        if (word.charAt(i) === "") {
          continue;
        }
        console.log("undefined symbol");
        preResult = "";
        continue;
      }
      results.push(preResult += word.charAt(i));
    }
    return results;
  };

  Input.addEventListener('keyup', streamWords, false);

  syntaxAnalys = function() {
    var j, k, l, len, len1, len2, len3, m, results, word;
    if (Convol[0][0] === 1 && Convol[0][1] === 0) {
      if (Convol[1][0] === 3) {
        if (Literals[Convol[1][1]][1] === false && Literals[Convol[1][1]][3] === false && Literals[Convol[1][1]][5] === false) {
          if (Convol[2][0] === 2 && Convol[2][1] === 0) {
            if (Convol[3][0] === 4) {
              if (Convol[4][0] === 2 && Convol[4][1] === 1) {
                if (Convol[5][0] === 4) {
                  if (Convol[6][0] === 2 && Convol[6][1] === 2) {
                    if (Convol[7][0] === 0) {
                      Literals[Convol[1][1]][5] = "ROWVECTOR";
                      Literals[Convol[1][1]][1] = Convol[3][1];
                      Literals[Convol[1][1]][2] = Convol[5][1];
                      deleteConvol();
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
    if (Convol[0][0] === 1 && Convol[0][1] === 1) {
      if (Convol[1][0] === 3) {
        if (Literals[Convol[1][1]][1] === false && Literals[Convol[1][1]][2] === false && Literals[Convol[1][1]][3] === false) {
          if (Convol[2][0] === 2 && Convol[2][1] === 0) {
            if (Convol[3][0] === 4) {
              if (Convol[4][0] === 2 && Convol[4][1] === 1) {
                if (Convol[5][0] === 4) {
                  if (Convol[6][0] === 2 && Convol[6][1] === 2) {
                    if (Convol[7][0] === 0) {
                      Literals[Convol[1][1]][5] = "COLVECTOR";
                      Literals[Convol[1][1]][1] = Convol[3][1];
                      Literals[Convol[1][1]][2] = Convol[5][1];
                      deleteConvol();
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
    if (Convol[0][0] === 1 && Convol[0][1] === 2) {
      if (Convol[1][0] === 3) {
        if (Literals[Convol[1][1]][1] === false && Literals[Convol[1][1]][2] === false && Literals[Convol[1][1]][3] === false) {
          if (Convol[2][0] === 2 && Convol[2][1] === 0) {
            if (Convol[3][0] === 2 && Convol[3][1] === 0) {
              if (Convol[4][0] === 4) {
                if (Convol[5][0] === 2 && Convol[5][1] === 1) {
                  if (Convol[6][0] === 4) {
                    if (Convol[7][0] === 2 && Convol[7][1] === 2) {
                      if (Convol[8][0] === 2 && Convol[8][1] === 0) {
                        if (Convol[9][0] === 4) {
                          if (Convol[10][0] === 2 && Convol[10][1] === 1) {
                            if (Convol[11][0] === 4) {
                              if (Convol[12][0] === 2 && Convol[12][1] === 2) {
                                if (Convol[13][0] === 2 && Convol[13][1] === 2) {
                                  if (Convol[14][0] === 0) {
                                    Literals[Convol[1][1]][5] = "MATRIX";
                                    Literals[Convol[1][1]][1] = Convol[4][1];
                                    Literals[Convol[1][1]][2] = Convol[6][1];
                                    Literals[Convol[1][1]][3] = Convol[9][1];
                                    Literals[Convol[1][1]][4] = Convol[11][1];
                                    deleteConvol();
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
    if (Convol[0][0] === 1 && Convol[0][1] === 3) {
      if (Convol[1][0] === 2 && Convol[1][1] === 0) {
        if (Convol[2][0] === 3) {
          if (Convol[3][0] === 2 && Convol[3][1] === 2) {
            if (Convol[4][0] === 0) {
              for (j = 0, len = Literals.length; j < len; j++) {
                word = Literals[j];
                if (word[0] === Literals[Convol[2][1]][0] && Literals[Convol[2][1]][5] !== false) {
                  console.log("PRINT IS...");
                  deleteConvol();
                }
              }
            }
          }
        }
      }
    }
    if (Convol[0][0] === 3) {
      for (k = 0, len1 = Literals.length; k < len1; k++) {
        word = Literals[k];
        if (word[0] === Literals[Convol[0][1]][0] && Literals[Convol[0][1]][5] === "ROWVECTOR" || Literals[Convol[0][1]][5] === "COLVECTOR") {
          if (Convol[1][0] === 2 && Convol[1][1] === 0) {
            if (Convol[2][0] === 4 && Convol[2][1] === '1' || Convol[2][1] === '2') {
              if (Convol[3][0] === 2 && Convol[3][1] === 2) {
                if (Convol[4][0] === 0) {
                  console.log("VECTOR " + Literals[Convol[0][1]][Convol[2][1]]);
                  deleteConvol();
                }
              }
            }
          }
        }
      }
    }
    if (Convol[0][0] === 3) {
      for (l = 0, len2 = Literals.length; l < len2; l++) {
        word = Literals[l];
        if (word[0] === Literals[Convol[0][1]][0] && Literals[Convol[0][1]][5] === "MATRIX") {
          if (Convol[1][0] === 2 && Convol[1][1] === 0) {
            if (Convol[2][0] === 4 && Convol[2][1] === '1' || Convol[2][1] === '2') {
              if (Convol[3][0] === 2 && Convol[3][1] === 1) {
                if (Convol[4][0] === 4 && Convol[4][1] === '1' || Convol[4][1] === '2') {
                  if (Convol[5][0] === 2 && Convol[5][1] === 2) {
                    if (Convol[6][0] === 0) {
                      if (Convol[2][1] === '1' && Convol[4][1] === '1') {
                        console.log("MATRIX " + Literals[Convol[0][1]][1]);
                      }
                      if (Convol[2][1] === '1' && Convol[4][1] === '2') {
                        console.log("MATRIX " + Literals[Convol[0][1]][2]);
                      }
                      if (Convol[2][1] === '2' && Convol[4][1] === '1') {
                        console.log("MATRIX " + Literals[Convol[0][1]][3]);
                      }
                      if (Convol[2][1] === '2' && Convol[4][1] === '2') {
                        console.log("MATRIX " + Literals[Convol[0][1]][4]);
                      }
                      deleteConvol();
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
    if (Convol[0][0] === 3) {
      results = [];
      for (m = 0, len3 = Literals.length; m < len3; m++) {
        word = Literals[m];
        if (word[0] === Literals[Convol[0][1]][0]) {
          if (Literals[Convol[0][1]][5] === "ROWVECTOR" || Literals[Convol[0][1]][5] === "COLVECTOR" || Literals[Convol[0][1]][5] === "MATRIX") {
            if (Convol[1][0] === 2 && Convol[1][1] === 3) {
              results.push(doBrackets());
            } else {
              results.push(void 0);
            }
          } else {
            results.push(void 0);
          }
        } else {
          results.push(void 0);
        }
      }
      return results;
    }
  };

  doBrackets = function() {
    var first_br, i, index1, index2, j, len, results, second_br, word;
    results = [];
    for (index1 = j = 0, len = Convol.length; j < len; index1 = ++j) {
      word = Convol[index1];
      if (word[0] === 2 && word[1] === 0) {
        first_br = index1 + 1;
        console.log("S(");
        index2 = first_br + 1;
        results.push((function() {
          var k, ref, ref1, results1;
          results1 = [];
          while (index2 < Convol.length) {
            console.log(index2);
            if (Convol[index2][0] === 2 && Convol[index2][1] === 2) {
              second_br = index2 - 1;
              console.log("S) ");
              doUnar(first_br, second_br);
              for (i = k = ref = first_br, ref1 = second_br; ref <= ref1 ? k <= ref1 : k >= ref1; i = ref <= ref1 ? ++k : --k) {
                console.log(Convol[i][0] + "is skob");
              }
              break;
            }
            results1.push(index2++);
          }
          return results1;
        })());
      } else {
        results.push(void 0);
      }
    }
    return results;
  };

  doUnar = function(begin_smb, end_smb) {
    var a, index, j, len, ref, results, word;
    ref = Convol.slice(begin_smb, +end_smb + 1 || 9e9);
    results = [];
    for (index = j = 0, len = ref.length; j < len; index = ++j) {
      word = ref[index];
      if (word[0] === 2 && word[1] === 7) {
        if (Convol[index - 1][0] === 3 && Literals[Convol[index - 1][1]][5] === "ROWVECTOR") {
          preRes.push(Literals[Convol[index - 1][1]]);
          preRes[preRes.length - 1][5] = "COLVECTOR";
          console.log(preRes);
          continue;
        } else if (Convol[index - 1][0] === 3 && Literals[Convol[index - 1][1]][5] === "COLVECTOR") {
          preRes.push(Literals[Convol[index - 1][1]]);
          preRes[preRes.length - 1][5] = "ROWVECTOR";
          console.log(preRes);
          continue;
        }
      }
      if (word[0] === 2 && word[1] === 8) {
        if (Convol[index - 1][0] === 3 && Literals[Convol[index - 1][1]][5] === "MATRIX") {
          preRes.push(Literals[Convol[index - 1][1]]);
          a = preRes[preRes.length - 1][2];
          preRes[preRes.length - 1][2] = preRes[preRes.length - 1][3];
          preRes[preRes.length - 1][3] = a;
          console.log(preRes);
          continue;
        } else {
          results.push(void 0);
        }
      } else {
        results.push(void 0);
      }
    }
    return results;
  };

  doTranspon = function(name, type_v) {
    var j, len, results, word;
    results = [];
    for (j = 0, len = Literals.length; j < len; j++) {
      word = Literals[j];
      if (word[0] === name && word[5] === "ROWVECTOR" || word[5] === "COLVECTOR") {
        if (type_v === "ROWVECTOR") {
          word[5] = "COLVECTOR";
        }
        if (word[5] === "COLVECTOR") {
          results.push(word[5] = "ROWVECTOR");
        } else {
          results.push(void 0);
        }
      } else {
        results.push(void 0);
      }
    }
    return results;
  };

  deleteConvol = function() {
    return Convol = [];
  };

  isKeyword = function(str, command) {
    var index, j, len, word;
    for (index = j = 0, len = Keywords.length; j < len; index = ++j) {
      word = Keywords[index];
      if (word === str) {
        Convol.push([1, index]);
        return true;
      }
    }
    return false;
  };

  isNumber = function(str, command) {
    if (("0" <= str && str <= "9")) {
      Convol.push([4, str]);
      value_command.push(str);
      console.log("courseos@razumov:~> " + str + " is number");
      return true;
    }
    return false;
  };

  isSeparator = function(str, command) {
    var index, j, len, word;
    for (index = j = 0, len = Separators.length; j < len; index = ++j) {
      word = Separators[index];
      if (word === str) {
        Convol.push([2, index]);
        console.log("courseos@razumov:~> " + Separators[index] + " is separator");
        return true;
      }
    }
    return false;
  };

  isLiteral = function(str, command) {
    var flag, index, j, len, word;
    if (("A" <= str && str <= "Z")) {
      flag = false;
      for (index = j = 0, len = Literals.length; j < len; index = ++j) {
        word = Literals[index];
        if (word[0] === str) {
          Convol.push([3, index]);
          console.log("courseos@razumov:~> " + str + " is literal");
          flag = true;
        }
      }
      if (flag === false) {
        console.log("courseos@razumov:~> " + str + " is new literal");
        Literals.push([str, false, false, false, false, false]);
        Convol.push([3, Literals.length - 1]);
      }
      return true;
    }
    return false;
  };

}).call(this);

//# sourceMappingURL=script.js.map
