// Generated by CoffeeScript 1.9.2
(function() {
  var Identifies, Input, Keywords, Literals, Output, Sepfretors, answer, lineNumbers, output;

  Input = document.getElementById("input-area");

  Output = document.getElementById("output-area");


  /*Database */

  Keywords = {
    1: "ROWVECTOR",
    2: "COLVECTOR",
    3: "MATRIX",
    4: "PRINT"
  };

  Sepfretors = {
    1: "(",
    2: ",",
    3: ")",
    4: "=",
    5: "+",
    6: "-",
    7: "*",
    8: "^",
    9: "@"
  };

  Identifies = {};

  Literals = {};

  lineNumbers = function() {
    var highLine, i, j, lowLine, results;
    highLine = document.getElementById("high-line-numbers");
    lowLine = document.getElementById("low-line-numbers");
    results = [];
    for (i = j = 1; j <= 50; i = ++j) {
      highLine.innerHTML += i + "\n";
      results.push(lowLine.innerHTML += i + "\n");
    }
    return results;
  };

  lineNumbers();

  output = function(answer) {
    return Output.innerHTML = "courseos@razumov:~>  " + answer;
  };

  answer = '';

  output(answer);

}).call(this);

//# sourceMappingURL=script.js.map
